-- MySQL Script generated by MySQL Workbench
-- Mon Jun 19 21:53:02 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ponto-professor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ponto-professor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ponto-professor` DEFAULT CHARACTER SET utf8 ;
USE `ponto-professor` ;

-- -----------------------------------------------------
-- Table `ponto-professor`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ponto-professor`.`curso` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ponto-professor`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ponto-professor`.`disciplina` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_curso` BIGINT(20) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `periodo` INT(11) NOT NULL,
  `descricao` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKncelm81kvdx8m08q5rbpn2jru` (`id_curso` ASC),
  CONSTRAINT `FKncelm81kvdx8m08q5rbpn2jru`
    FOREIGN KEY (`id_curso`)
    REFERENCES `ponto-professor`.`curso` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ponto-professor`.`disciplina_horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ponto-professor`.`disciplina_horario` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_disciplina` BIGINT(20) NOT NULL,
  `dia` VARCHAR(255) NOT NULL,
  `turno` VARCHAR(255) NOT NULL,
  `de_horario` TIME NOT NULL,
  `ate_horario` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKjlgbmrk7equrbo6cja16cdokx` (`id_disciplina` ASC),
  CONSTRAINT `FKjlgbmrk7equrbo6cja16cdokx`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `ponto-professor`.`disciplina` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ponto-professor`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ponto-professor`.`professor` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `sobre_nome` VARCHAR(80) NOT NULL,
  `matricula` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ponto-professor`.`frequencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ponto-professor`.`frequencia` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_curso` BIGINT(20) NOT NULL,
  `id_disciplina` BIGINT(20) NOT NULL,
  `id_professor` BIGINT(20) NOT NULL,
  `conteudo_programado` LONGTEXT NULL DEFAULT NULL,
  `registro_entrada` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `registro_saida` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKs0l1upem7tbsji5xiupjr267s` (`id_curso` ASC),
  INDEX `FKqx8kr59tfkhriyjtoepiwq0kw` (`id_disciplina` ASC),
  INDEX `FKtbvetdyj05xfexv8qr41v52d6` (`id_professor` ASC),
  CONSTRAINT `FKqx8kr59tfkhriyjtoepiwq0kw`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `ponto-professor`.`disciplina` (`id`),
  CONSTRAINT `FKs0l1upem7tbsji5xiupjr267s`
    FOREIGN KEY (`id_curso`)
    REFERENCES `ponto-professor`.`curso` (`id`),
  CONSTRAINT `FKtbvetdyj05xfexv8qr41v52d6`
    FOREIGN KEY (`id_professor`)
    REFERENCES `ponto-professor`.`professor` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
